name: ring_tone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_cli: ^1.8.1
  animated_card: ^2.0.0
  elegant_radio_button_group: ^0.0.1
  flutter: 
    sdk: flutter
  flutter_share: ^2.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

